#!/usr/bin/env zsh
set -eo pipefail

autoload -Uz colors; colors

ef() {
  printf "${bold_color}${fg[white]}$1${reset_color}" "${@:2}"
}

e() {
  ef "$1\n" "${@:2}"
}

delete-rogue() {
  e '%s' "Deleting any rouge k8s objects" >&2

  for i in deployment service job replicaset pod secret configmap pvc; do
    ef '- [%ss]: ' $i
    kubectl delete $i -l heritage=Tiller
  done

  ef '- [%ss]: ' "kube-system:configmap"
  kubectl -n kube-system delete configmap --selector=OWNER=TILLER
}

helm=($HELM_BIN --host $TILLER_HOST)
releases_raw=$(helm list --short)
releases=(${(f)releases_raw})

if [ $#releases -gt 0 ]; then
  e '%s' "Deleting all releases:" >&2

  for r in $releases; do
    printf '- %s\n' $r
  done
  echo

  for r in $releases; do
    ef '- [release %s]: ' $i
    $helm delete --purge $r

    e "${fg[red]}${fg[white]} Deleted release: %s" $r >&2
  done
fi

delete-rogue

e "${fg[green]}%s" "Done!"
